### PR TITLE
add chi-square and anova p-values and update tests

### LINKED ISSUE #6: Add p-value to descriptives table
Add p-value for descriptives table by default when a treatment is specified. No argument?

### PR DESCRIPTION
**Pull request by MBattagl**
Tests for this package are weird, and assume that the current version is accurate. Still moderately useful, as we do want to know if any of our output changes if we make code changes. 

I added tests for the p-value functions comparing them to the base functions, which seems like a better approach. Should we be doing tests like this for more of the internals?

Closes #6

### CODE REVIEW

**Review by scheidec — COMMENTED** [review]
Yes, where possible we should be comparing every output to the corresponding base function output when testing.   Instead of manually entering the output from previous versions of the function in the test, is it feasible to build the table from scratch using base functions in the test script as a comparison?

**Comment by MBattagl** [comment]
> Yes, where possible we should be comparing every output to the corresponding base function output when testing. Instead of manually entering the output from previous versions of the function in the test, is it feasible to build the table from scratch using base functions in the test script as a comparison?

Probably not. It would just be copy and pasting the source code

**Comment by scheidec** [comment]
Yeah that's what I assumed.  I think of the internal `helpers.R` functions, `p_kruskal` should also be tested somewhere.  You can also remove the `weighted_quantile` function for now since it's not used yet.

**Comment by MBattagl** [comment]
`p_kruskal` is not used yet since median/IQR functionality is not implemented. Just remove both for now?

**Comment by scheidec** [comment]
Sure, go ahead and remove any of the internals that aren't used yet.

**Comment by MBattagl** [comment]
I removed all the unused functions from the helper file. Give it another look, and then we can merge

**Comment by scheidec** [comment]
Looks good. Go ahead and rebase and merge.

**Pull request merged**
