### PR TITLE
added weighting functionality to descriptives

### LINKED ISSUE #7: Add weighting functionality

### PR DESCRIPTION
**Pull request by MBattagl**
Weighting functionality is mostly ready to go.

One last decision is how (if) we should handle normalization of weights. With current functionality, the only place this matters is when calculating weighted chi-square. The sample size in a weighted chisq test is the sum of the weights, which influences the p-value. 

In the propensity score case, we want our weights to average 1 (sum to the number of observations). Propensity score weights don't typically have a mean of 1, especially with unbalanced treatment groups, so this either needs to be done by the user or handled by our functions. On the other hand if the user is using frequency weights, they may actually want the weights to change the sample size. 

In this example, I think we typically want 0.855 to be returned in both cases. 
```
> example_dat %>%
+   mutate(wt = 1) %>%
+   tibbletest:::p_chi_fisher(var = "happy", treatment = "treat", weight_var = "wt")
[1] 0.8553563
> example_dat %>%
+   mutate(wt = 10) %>%
+   tibbletest:::p_chi_fisher(var = "happy", treatment = "treat", weight_var = "wt")
[1] 0.2096383
```

Closes #7

### CODE REVIEW

**Comment by scheidec** [comment]
I don't think the function should normalize weights automatically.  We should leave that decision up to the user to perform beforehand.  Since propensity score weights would be generated outside of the function, the normalization should also occur prior to use, and we can explain that in the walkthrough in the README.

**Comment by MBattagl** [comment]
If we want weights to be treated as frequency (replication) weights, we'll need to find another way to calculate anova. The approaches I've found rely on the `weights` argument in `lm` , which treats the weights as sampling weights. The `survey` functions also treat weights as sampling weights. `survey`'s tests are also done without using maximum likelihood, so when we pass in weights of 1 they give different results then `stats` tests.

Edit: The correct term for `lm` and `survey` weights are "analytic weights"

**Comment by scheidec** [comment]
It sounds like no matter what we'll have to add an argument specifying whether to treat as sampling weights or replication weights, even if there is a function that can perform anova with replication weights.  For our purposes, I don't think we'll be using replication weights often, so maybe tag that as a future issue to pursue further if needed?  If we leave it at that then we'll just need to clarify in documentation that the `weight_var` argument is for sampling weights only.

**Comment by MBattagl** [comment]
If the user passes in weights where the mean doesn't equal 1, should we:
1. Silently normalize
2. Normalize with message or warning
3. Error and force user to normalize themselves

(1) is what other packages do and it's fine probably fine as long as the docs are clear? (2) is probably the right thing to do, but don't want to needlessly make users think something is wrong.

**Comment by MBattagl** [comment]
Speaking of propensity scores not being normalized by other packages, would a function that calculates propensity score weights be within the scope of this package?

It would take `df`, `treatment`, and `ivs` as arguments, use random forest for the propensity score calculation, normalize (divide by mean) the propensity score weights, and return the original dataframe with weights as a new column.

**Comment by scheidec** [comment]
I like option (2).  Might as well return a message to make the user aware that the weights were normalized.

That's a great idea to add a propensity score weighting function.  Definitely fits into the workflow that the package is getting setup for.  Go ahead and add an issue for it.

**Comment by MBattagl** [comment]
Ready for review

**Review by scheidec — APPROVED** [review]
Looks good. Go ahead and merge.

**Pull request merged**
